version: '3.8'

services:
  web: &web_base
    tty: true
    stdin_open: true
    command: sh /docker-entrypoint.sh
    build: ./docker/web
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - bundle_caches:/app/vendor/bundle
    environment:
      HOST: localhost
      PORT: 3000
volumes:
  bundle_caches:
